# For use with cargo deny.
# https://embarkstudios.github.io/cargo-deny/index.html

[licenses]
version = 2
unused-allowed-license = "warn"
confidence-threshold = 1.0
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2016",
]
