name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all-features
    - name: Build w/o features
      run: cargo build --verbose --no-default-features --features github-actions-hack
    - name: Test documentation
      run: cargo doc --examples --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Lint
      run: cargo clippy --examples --verbose --all-features
