name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux dependencies
      run: sudo apt-get install -y libasound2-dev ; sudo apt-get install -y libwebkit2gtk-4.0

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose -F github-actions
    - name: Build w/o features
      run: cargo build --verbose --no-default-features -F github-actions-hack
    - name: Test documentation
      run: cargo doc --examples --verbose -F github-actions
    - name: Run tests
      run: cargo test --verbose -F github-actions
    - name: Lint
      run: cargo clippy --examples --verbose -F github-actions
