name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features github-actions-hack
    - name: Run tests
      run: cargo test --verbose --features github-actions-hack
    - name: Lint
      run: cargo clippy --verbose --features github-actions-hack
